import { Request, Response } from "express";
import { ApiResponse } from "../../../common/utils/ApiResponse";
import logger from "../../../common/utils/logger";

/**
 * Create a new patient
 * Validation is handled by Zod middleware before this controller runs
 */
export const createPatient = async (req: Request, res: Response) => {
  try {
    // req.body is already validated and typed by Zod middleware
    const patientData = req.body;

    // Simulate patient creation logic (e.g., database operation)
    const newPatient = {
      id: "generated-patient-id", // This would be generated by the database
      ...patientData,
    };

    return ApiResponse.created(res, "Patient created successfully", {
      id: newPatient.id,
    });
  } catch (err: any) {
    const status = err?.statusCode || 500;
    const message = err?.message || "Internal Server Error";

    // Log errors (moderate level - just the essentials)
    logger.error("Error creating patient", {
      error: message,
      statusCode: status,
      email: req.body?.email,
    });

    return ApiResponse.error(res, message, status);
  }
};
